// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB75tTjBQjk25Z82-Bi4O2k7dBd2UOm3ws',
    appId: '1:5882605875:web:aab403381d95fb7e568e46',
    messagingSenderId: '5882605875',
    projectId: 'mualij-54a30',
    authDomain: 'mualij-54a30.firebaseapp.com',
    storageBucket: 'mualij-54a30.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAnQGG0MzH-v8s2X9MKi5nc2l1zbe4H4NU',
    appId: '1:5882605875:android:d7b02320296d7695568e46',
    messagingSenderId: '5882605875',
    projectId: 'mualij-54a30',
    storageBucket: 'mualij-54a30.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCBD6SRehPQfPEEhnXyARitEVcHm_1jn-s',
    appId: '1:5882605875:ios:759524100da2c2d2568e46',
    messagingSenderId: '5882605875',
    projectId: 'mualij-54a30',
    storageBucket: 'mualij-54a30.appspot.com',
    iosClientId: '5882605875-r7i8q0ti47hldm8lq2mlsql8g6gre44n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mualij',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCBD6SRehPQfPEEhnXyARitEVcHm_1jn-s',
    appId: '1:5882605875:ios:759524100da2c2d2568e46',
    messagingSenderId: '5882605875',
    projectId: 'mualij-54a30',
    storageBucket: 'mualij-54a30.appspot.com',
    iosClientId: '5882605875-r7i8q0ti47hldm8lq2mlsql8g6gre44n.apps.googleusercontent.com',
    iosBundleId: 'com.example.mualij',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB75tTjBQjk25Z82-Bi4O2k7dBd2UOm3ws',
    appId: '1:5882605875:web:2b1bad16c08e5738568e46',
    messagingSenderId: '5882605875',
    projectId: 'mualij-54a30',
    authDomain: 'mualij-54a30.firebaseapp.com',
    storageBucket: 'mualij-54a30.appspot.com',
  );
}
